-- LearningSentence 초기 데이터 100개

-- 일상회화 (초급)
INSERT INTO LEARNING_SENTENCE (sentence, translation, created_date, modified_date) VALUES
('Hello, how are you?', '안녕하세요, 어떻게 지내세요?', now(), now()),
('I am fine, thank you.', '저는 잘 지내요, 감사합니다.', now(), now()),
('What is your name?', '당신의 이름은 무엇인가요?', now(), now()),
('My name is John.', '제 이름은 John입니다.', now(), now()),
('Nice to meet you.', '만나서 반가워요.', now(), now()),
('Where are you from?', '어디서 오셨나요?', now(), now()),
('I am from Korea.', '저는 한국에서 왔어요.', now(), now()),
('How old are you?', '몇 살이신가요?', now(), now()),
('I am twenty years old.', '저는 스무 살입니다.', now(), now()),
('What time is it?', '몇 시인가요?', now(), now()),
('It is three o''clock.', '3시입니다.', now(), now()),
('What day is today?', '오늘은 무슨 요일인가요?', now(), now()),
('Today is Monday.', '오늘은 월요일입니다.', now(), now()),
('What is the weather like?', '날씨가 어때요?', now(), now()),
('It is sunny today.', '오늘은 맑아요.', now(), now()),
('Do you like coffee?', '커피를 좋아하시나요?', now(), now()),
('Yes, I love coffee.', '네, 커피를 정말 좋아해요.', now(), now()),
('What is your favorite food?', '가장 좋아하는 음식은 무엇인가요?', now(), now()),
('I like pizza the most.', '저는 피자를 가장 좋아해요.', now(), now()),
('Can you help me?', '도와주실 수 있나요?', now(), now()),
('Of course, I will help you.', '물론이죠, 도와드릴게요.', now(), now());

-- 일상회화 (중급)
INSERT INTO LEARNING_SENTENCE (sentence, translation, created_date, modified_date) VALUES
('I have been studying English for two years.', '저는 영어를 2년 동안 공부해왔습니다.', now(), now()),
('She is the most beautiful person I have ever met.', '그녀는 제가 만난 사람 중 가장 아름다운 사람입니다.', now(), now()),
('If I had known about the meeting, I would have attended.', '회의에 대해 알고 있었다면 참석했을 텐데요.', now(), now()),
('The movie that we watched last night was really interesting.', '어젯밤에 본 영화는 정말 재미있었어요.', now(), now()),
('I am looking forward to seeing you next week.', '다음 주에 뵙기를 기대하고 있어요.', now(), now()),
('It has been a long time since we last met.', '마지막으로 만난 지 오래되었네요.', now(), now()),
('I would appreciate it if you could help me with this.', '이것을 도와주시면 감사하겠습니다.', now(), now()),
('The restaurant where we had dinner was excellent.', '저녁을 먹은 식당은 훌륭했어요.', now(), now()),
('I am not sure whether I can make it to the party.', '파티에 갈 수 있을지 확실하지 않아요.', now(), now()),
('This is the best book I have ever read.', '이것은 제가 읽은 책 중 최고입니다.', now(), now()),
('I am sorry, but I cannot agree with your opinion.', '죄송하지만 당신의 의견에 동의할 수 없어요.', now(), now()),
('The weather has been getting worse lately.', '최근에 날씨가 점점 나빠지고 있어요.', now(), now()),
('I am thinking about moving to a new apartment.', '새로운 아파트로 이사하는 것을 생각하고 있어요.', now(), now()),
('It seems like everyone is busy these days.', '요즘 모두가 바쁜 것 같아요.', now(), now()),
('I have never been to that country before.', '저는 그 나라에 가본 적이 없어요.', now(), now()),
('The concert was so amazing that I could not believe it.', '콘서트가 너무 놀라워서 믿을 수 없었어요.', now(), now()),
('I am afraid I cannot attend the meeting tomorrow.', '죄송하지만 내일 회의에 참석할 수 없을 것 같아요.', now(), now()),
('This is exactly what I was looking for.', '이것이 바로 제가 찾고 있던 것입니다.', now(), now()),
('I am not used to waking up early in the morning.', '저는 아침 일찍 일어나는 것에 익숙하지 않아요.', now(), now()),
('The movie starts at 8 PM, so we should leave by 7:30.', '영화가 오후 8시에 시작하니까 7시 30분까지는 출발해야 해요.', now(), now()),
('I am really excited about the upcoming vacation.', '다가오는 휴가에 대해 정말 기대되고 있어요.', now(), now());

-- 비즈니스 (초급)
INSERT INTO LEARNING_SENTENCE (sentence, translation, created_date, modified_date) VALUES
('Good morning, everyone.', '좋은 아침입니다, 여러분.', now(), now()),
('Thank you for your time.', '시간을 내주셔서 감사합니다.', now(), now()),
('I would like to introduce myself.', '자기소개를 하고 싶습니다.', now(), now()),
('Let me know if you have any questions.', '질문이 있으시면 알려주세요.', now(), now()),
('I will send you the report tomorrow.', '내일 보고서를 보내드리겠습니다.', now(), now()),
('Could you please repeat that?', '그것을 다시 한 번 말씀해 주실 수 있나요?', now(), now()),
('I agree with your proposal.', '당신의 제안에 동의합니다.', now(), now()),
('We need to schedule a meeting.', '회의 일정을 잡아야 합니다.', now(), now()),
('The deadline is next Friday.', '마감일은 다음 주 금요일입니다.', now(), now()),
('I will get back to you soon.', '곧 연락드리겠습니다.', now(), now()),
('Please send me the documents.', '문서를 보내주세요.', now(), now()),
('I am looking forward to our meeting.', '우리의 회의를 기대하고 있습니다.', now(), now()),
('Thank you for your cooperation.', '협조해 주셔서 감사합니다.', now(), now()),
('I apologize for the inconvenience.', '불편을 끼쳐 죄송합니다.', now(), now()),
('We will review your application.', '귀하의 신청서를 검토하겠습니다.', now(), now()),
('The project is on schedule.', '프로젝트가 일정에 맞춰 진행되고 있습니다.', now(), now()),
('I need your approval for this.', '이것에 대한 승인이 필요합니다.', now(), now()),
('Let us discuss this further.', '이것에 대해 더 논의해 보겠습니다.', now(), now()),
('I will keep you updated.', '최신 정보를 계속 알려드리겠습니다.', now(), now()),
('We appreciate your business.', '귀하의 거래를 감사하게 생각합니다.', now(), now()),
('Please confirm your attendance.', '출석을 확인해 주세요.', now(), now());

-- 비즈니스 (중급)
INSERT INTO LEARNING_SENTENCE (sentence, translation, created_date, modified_date) VALUES
('I would like to propose a new strategy for our marketing campaign.', '마케팅 캠페인을 위한 새로운 전략을 제안하고 싶습니다.', now(), now()),
('We have been experiencing some challenges with the current system.', '현재 시스템에서 몇 가지 문제를 겪고 있습니다.', now(), now()),
('I believe this approach will significantly improve our efficiency.', '이 접근 방식이 우리의 효율성을 크게 향상시킬 것이라고 믿습니다.', now(), now()),
('The quarterly results exceeded our expectations by 15%.', '분기별 결과가 우리의 기대치를 15% 초과했습니다.', now(), now()),
('We need to allocate more resources to this project.', '이 프로젝트에 더 많은 자원을 할당해야 합니다.', now(), now()),
('I would appreciate your feedback on the proposal.', '제안서에 대한 피드백을 받고 싶습니다.', now(), now()),
('The market research indicates a growing demand for our product.', '시장 조사는 우리 제품에 대한 수요가 증가하고 있음을 보여줍니다.', now(), now()),
('We should consider alternative solutions to address this issue.', '이 문제를 해결하기 위한 대안을 고려해야 합니다.', now(), now()),
('The implementation of the new policy has been successful so far.', '새로운 정책의 시행은 지금까지 성공적이었습니다.', now(), now()),
('I would like to schedule a follow-up meeting to discuss the details.', '세부사항을 논의하기 위한 후속 회의 일정을 잡고 싶습니다.', now(), now()),
('The team has been working diligently to meet the deadline.', '팀이 마감일을 맞추기 위해 부지런히 일하고 있습니다.', now(), now()),
('We have identified several areas for improvement in our process.', '우리 프로세스에서 개선이 필요한 몇 가지 영역을 파악했습니다.', now(), now()),
('The client expressed satisfaction with our recent delivery.', '고객이 우리의 최근 납품에 만족을 표현했습니다.', now(), now()),
('I recommend that we proceed with the current plan.', '현재 계획을 진행하는 것을 권장합니다.', now(), now()),
('We need to establish clear communication channels.', '명확한 의사소통 채널을 구축해야 합니다.', now(), now()),
('The budget allocation has been approved by the board.', '예산 할당이 이사회에서 승인되었습니다.', now(), now()),
('I would like to address the concerns raised in the previous meeting.', '이전 회의에서 제기된 우려사항을 다루고 싶습니다.', now(), now()),
('We have been monitoring the situation closely.', '상황을 면밀히 모니터링하고 있습니다.', now(), now()),
('The new software has significantly improved our productivity.', '새로운 소프트웨어가 우리의 생산성을 크게 향상시켰습니다.', now(), now()),
('I suggest we conduct a thorough review of our procedures.', '우리 절차에 대한 철저한 검토를 수행하는 것을 제안합니다.', now(), now()),
('We appreciate your continued support and cooperation.', '지속적인 지원과 협조에 감사드립니다.', now(), now());

-- 여행 (초급)
INSERT INTO LEARNING_SENTENCE (sentence, translation, created_date, modified_date) VALUES
('Where is the nearest hotel?', '가장 가까운 호텔은 어디인가요?', now(), now()),
('How much does this cost?', '이것은 얼마인가요?', now(), now()),
('I would like to book a room.', '방을 예약하고 싶습니다.', now(), now()),
('What time does the train leave?', '기차는 몇 시에 출발하나요?', now(), now()),
('Can you show me the way?', '길을 보여주실 수 있나요?', now(), now()),
('I am lost.', '길을 잃었습니다.', now(), now()),
('Do you speak English?', '영어를 하시나요?', now(), now()),
('I do not understand.', '이해하지 못합니다.', now(), now()),
('Where can I buy tickets?', '어디서 표를 살 수 있나요?', now(), now()),
('What is the exchange rate?', '환율은 얼마인가요?', now(), now()),
('I need a map.', '지도가 필요합니다.', now(), now()),
('How far is it to the airport?', '공항까지 얼마나 멀리 있나요?', now(), now()),
('Can you recommend a good restaurant?', '좋은 식당을 추천해 주실 수 있나요?', now(), now()),
('I would like to rent a car.', '차를 빌리고 싶습니다.', now(), now()),
('What is the weather like tomorrow?', '내일 날씨는 어때요?', now(), now()),
('Where is the tourist information center?', '관광 안내소는 어디인가요?', now(), now()),
('I need to change money.', '돈을 바꿔야 합니다.', now(), now()),
('What time does the museum open?', '박물관은 몇 시에 열리나요?', now(), now()),
('Can you take a picture for me?', '사진을 찍어 주실 수 있나요?', now(), now()),
('I am allergic to seafood.', '저는 해산물 알레르기가 있습니다.', now(), now()),
('Where is the nearest hospital?', '가장 가까운 병원은 어디인가요?', now(), now());

-- 여행 (중급)
INSERT INTO LEARNING_SENTENCE (sentence, translation, created_date, modified_date) VALUES
('I have been planning this trip for months and I am really excited about it.', '이 여행을 몇 달 동안 계획해왔고 정말 기대되고 있어요.', now(), now()),
('The local cuisine was absolutely delicious and exceeded my expectations.', '현지 요리는 절대적으로 맛있었고 제 기대를 뛰어넘었습니다.', now(), now()),
('I would recommend visiting this place during the off-season to avoid crowds.', '군중을 피하기 위해 비수기에 이 곳을 방문하는 것을 권장합니다.', now(), now()),
('The tour guide was very knowledgeable and provided interesting historical facts.', '가이드는 매우 박식했고 흥미로운 역사적 사실들을 제공했습니다.', now(), now()),
('We encountered some unexpected weather conditions during our hike.', '등산하는 동안 예상치 못한 날씨 조건을 만났습니다.', now(), now()),
('The hotel staff went above and beyond to make our stay comfortable.', '호텔 직원들은 우리의 숙박을 편안하게 만들기 위해 최선을 다했습니다.', now(), now()),
('I suggest booking your accommodation well in advance, especially during peak season.', '특히 성수기에는 숙박시설을 미리 예약하는 것을 제안합니다.', now(), now()),
('The transportation system in this city is very efficient and easy to navigate.', '이 도시의 교통 시스템은 매우 효율적이고 이용하기 쉽습니다.', now(), now()),
('We had the opportunity to experience the local culture firsthand.', '현지 문화를 직접 경험할 기회를 가졌습니다.', now(), now()),
('The sunset view from the mountain top was absolutely breathtaking.', '산 정상에서의 일몰 경치는 절대적으로 숨 막힐 정도로 아름다웠습니다.', now(), now()),
('I would advise bringing comfortable walking shoes for this type of trip.', '이런 종류의 여행에는 편안한 걷기 신발을 가져가는 것을 권장합니다.', now(), now()),
('The local market was filled with unique souvenirs and traditional crafts.', '현지 시장은 독특한 기념품과 전통 공예품으로 가득했습니다.', now(), now()),
('We were fortunate to witness a traditional festival during our visit.', '방문하는 동안 전통 축제를 목격할 수 있어서 운이 좋았습니다.', now(), now()),
('The historical sites we visited were well-preserved and informative.', '방문한 역사적 장소들은 잘 보존되어 있고 정보가 풍부했습니다.', now(), now()),
('I recommend trying the local specialties, even if they seem unusual at first.', '처음에는 이상하게 보일지라도 현지 특산품을 시도해보는 것을 권장합니다.', now(), now()),
('The natural scenery in this region is absolutely stunning and worth the long journey.', '이 지역의 자연 경치는 절대적으로 놀랍고 긴 여행을 할 가치가 있습니다.', now(), now()),
('We learned a lot about the local customs and traditions from our hosts.', '주인으로부터 현지 관습과 전통에 대해 많이 배웠습니다.', now(), now()),
('The weather forecast was accurate, which helped us plan our activities accordingly.', '일기 예보가 정확해서 우리의 활동을 그에 맞게 계획할 수 있었습니다.', now(), now()),
('I would suggest visiting this destination during the spring when the flowers are in bloom.', '꽃이 피는 봄에 이 목적지를 방문하는 것을 제안합니다.', now(), now()),
('The local people were incredibly friendly and welcoming to tourists.', '현지 사람들은 관광객들에게 믿을 수 없을 정도로 친절하고 환영했습니다.', now(), now());

